color_palette <- function(id) {
  moduleServer(id,
               
               function(input, output, session) {
                 mycolor <- reactive({
                   mycolor <- data.frame(
                     color = c(
                       '#afeeee',
                       '#faf0e6',
                       '#3cb371',
                       '#800000',
                       '#b22222',
                       '#d2b48c',
                       '#228b22',
                       '#778899',
                       '#90ee90',
                       '#cd853f',
                       '#808000',
                       '#808080',
                       '#191970',
                       '#708090',
                       '#d2691e',
                       '#008000',
                       '#dcdcdc',
                       '#ffa500',
                       '#9400d3',
                       '#7b68ee',
                       '#40e0d0',
                       '#ffc0cb',
                       '#7fff00',
                       '#e6e6fa',
                       '#db7093',
                       '#66cdaa',
                       '#e9967a',
                       '#eee8aa',
                       '#48d1cc',
                       '#ff8c00',
                       '#556b2f',
                       '#ee82ee',
                       '#deb887',
                       '#808080',
                       '#008b8b',
                       '#b0c4de',
                       '#9acd32',
                       '#00ced1',
                       '#a52a2a',
                       '#008080',
                       '#ff00ff',
                       '#f4a460',
                       '#663399',
                       '#b8860b',
                       '#6b8e23',
                       '#dda0dd',
                       '#778899',
                       '#f5deb3',
                       '#0000ff',
                       '#ffd700',
                       '#e0ffff',
                       '#c71585',
                       '#2f4f4f',
                       '#6495ed',
                       '#f08080',
                       '#32cd32',
                       '#daa520',
                       '#5f9ea0',
                       '#006400',
                       '#2f4f4f',
                       '#87ceeb',
                       '#ff0000',
                       '#708090',
                       '#c0c0c0',
                       '#ff69b4',
                       '#8b4513',
                       '#20b2aa',
                       '#0000cd',
                       '#8b0000',
                       '#1e90ff',
                       '#a0522d',
                       '#ffb6c1',
                       '#dc143c',
                       '#f5fffa',
                       '#fafad2',
                       '#b0e0e6',
                       '#4169e1',
                       '#d3d3d3',
                       '#00008b',
                       '#bc8f8f',
                       '#f5f5dc',
                       '#4682b4',
                       '#00ff7f',
                       '#00ff00',
                       '#ff7f50',
                       '#f5f5f5',
                       '#2e8b57',
                       '#ff6347',
                       '#a9a9a9',
                       '#483d8b',
                       '#696969',
                       '#00bfff',
                       '#f0e68c',
                       '#9932cc',
                       '#faebd7',
                       '#ff4500',
                       '#00fa9a',
                       '#fdf5e6',
                       '#d8bfd8',
                       '#9370db',
                       '#ff00ff',
                       '#7fffd4',
                       '#d3d3d3',
                       '#adff2f',
                       '#f8f8ff',
                       '#add8e6',
                       '#98fb98',
                       '#ba55d3',
                       '#ffa07a',
                       '#fa8072',
                       '#a9a9a9',
                       '#696969',
                       '#8b008b',
                       '#ff1493',
                       '#7cfc00',
                       '#87cefa',
                       '#cd5c5c',
                       '#da70d6',
                       '#8a2be2',
                       '#4b0082',
                       '#800080',
                       '#bdb76b',
                       '#6a5acd',
                       '#8fbc8f'
                     )
                   )
                   
                   mycolor1 <-
                     as.data.frame(mycolor[sample(1:nrow(mycolor)), ])

                   mycolor2 <-
                     as.data.frame(mycolor1[sample(1:nrow(mycolor1)), ])

                   names(mycolor2) <- c('color')

                   mycolor2
                   
                 })
                 
                 
                 return(mycolor)
                 
               })
  
}